# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - listen.md
  - biography.md
  - cv.md
  - links.md
  - contact.md

style: light 

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

domain: lucaspanedda.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: lucaspanedda.github.io  # the base hostname and protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag
